# Generated by Django 3.1.5 on 2021-01-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actorId', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Phone', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=30, null=True)),
                ('Rating', models.CharField(max_length=10, null=True)),
                ('Rental_duration', models.CharField(max_length=10, null=True)),
                ('Length', models.CharField(max_length=10, null=True)),
                ('Special_features', models.TextField(null=True)),
                ('Description', models.TextField(null=True)),
                ('actors', models.ManyToManyField(to='jsonarapi.Actors')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('rentalId', models.AutoField(primary_key=True, serialize=False)),
                ('Rental_Date', models.DateTimeField(null=True)),
                ('Return_Date', models.DateTimeField(null=True)),
                ('CustomerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonarapi.customers')),
                ('FilmId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonarapi.films')),
                ('StaffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonarapi.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(null=True)),
                ('Payment_Date', models.DateTimeField(null=True)),
                ('CustomerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonarapi.customers')),
                ('rental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonarapi.rentals')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonarapi.staff')),
            ],
        ),
    ]
