# Generated by Django 3.1.2 on 2021-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonarapi', '0002_auto_20210128_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='Actors',
            field=models.ManyToManyField(to='jsonarapi.Actors'),
        ),
    ]
